name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
jobs:         
  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'VortexExpansion/KurocoNext' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
        # - name: Zip artifact for upload
        #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: out
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://sushipedia.g.kuroco.app/direct/menu/github/"
          webhook_secret: "8d90dc3cca20f1c207ce5e4c5d357742"
          data: '{"single_zip":"0","domain":"sushipedia.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
